services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb_new
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: testdb_new
      DB_USER: testuser
      DB_PASSWORD: testpassword
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_BASE: ${OPENAI_API_BASE:-https://api.openai.com/v1}
      DATABASE_URL: mysql+pymysql://testuser:testpassword@mysql:3306/testdb_new
      PYTHONPATH: /app
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - BACKEND_URL=http://backend:8000

volumes:
  mysql_data:
