"""ensure_interview_log_and_relations_for_multi_turn

Revision ID: 15fabd3ea79e
Revises: 5f34d4e74e62
Create Date: 2025-05-16 10:39:37.799836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15fabd3ea79e'
down_revision = '5f34d4e74e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
