"""set_null_on_delete_for_interviewlog_question_fk

Revision ID: 1bfba25a1af9
Revises: 15fabd3ea79e
Create Date: 2025-05-16 12:03:20.180548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bfba25a1af9'
down_revision = '15fabd3ea79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('interview_logs_ibfk_2', 'interview_logs', type_='foreignkey')
    op.create_foreign_key(None, 'interview_logs', 'questions', ['question_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_logs', type_='foreignkey')
    op.create_foreign_key('interview_logs_ibfk_2', 'interview_logs', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
