""""add_source_dialogue_to_reports"

Revision ID: 60149994d9c7
Revises: 3ee062c1afd0
Create Date: 2025-05-17 10:25:55.738212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60149994d9c7'
down_revision = '3ee062c1afd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('source_dialogue', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'source_dialogue')
    # ### end Alembic commands ###
