"""add_speaker_role_to_interview_log

Revision ID: 6d72a0398d8b
Revises: 60149994d9c7
Create Date: 2025-05-17 17:09:28.576272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# from sqlalchemy.dialects import mysql # 如果您使用MySQL并且需要特定的ENUM定义，可以取消注释


# revision identifiers, used by Alembic.
revision: str = '6d72a0398d8b' # 保留 Alembic 生成的值
down_revision: Union[str, None] = '60149994d9c7' # 保留 Alembic 生成的值
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# 定义 SpeakerRole 枚举的名称，以便在迁移脚本中引用
# 注意：这里的 name='speakerrole' 必须与您数据库中实际创建的ENUM类型名称匹配（通常是小写）
# SQLAlchemy 的 DBEnum(SpeakerRole) 通常会生成名为 'speakerrole' (小写) 的数据库ENUM类型。
speaker_role_enum = sa.Enum('INTERVIEWER', 'CANDIDATE', 'SYSTEM', name='speakerrole')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 对于某些数据库如PostgreSQL，如果ENUM类型尚不存在，下面的add_column会尝试创建它。
    # 如果您的数据库是MySQL，它会将ENUM作为列类型的一部分。
    # 对于更复杂的场景或特定的数据库行为，您可能需要显式创建ENUM类型，
    # 例如： op.execute("CREATE TYPE speakerrole AS ENUM ('INTERVIEWER', 'CANDIDATE', 'SYSTEM')")
    # 但通常让SQLAlchemy通过sa.Enum处理是更可移植的方式。

    op.add_column('interview_logs', 
                  sa.Column('speaker_role', 
                            speaker_role_enum, 
                            nullable=False,
                            # 考虑到 nullable=False，为现有行提供一个默认值。
                            # 如果您的表是空的，或者您将在之后手动填充，可以不设置 server_default。
                            # 如果不设置，并且表中有数据，迁移可能会失败。
                            # 您可以选择 'INTERVIEWER', 'CANDIDATE', 或 'SYSTEM' 作为默认值。
                            # 这里以 'SYSTEM' 为例，您可能需要根据实际情况调整。
                            server_default='SYSTEM' 
                           )
                 )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_logs', 'speaker_role')
    
    # 如果在 upgrade() 中显式创建了 ENUM 类型 (例如用 op.execute for PostgreSQL),
    # 那么在这里也需要显式删除它：
    # op.execute("DROP TYPE speakerrole")

    # ### end Alembic commands ###
