"""add_analyzed_description_to_jobs_table

Revision ID: 770db16e4252
Revises: 6d72a0398d8b
Create Date: 2025-05-17 20:38:35.626893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770db16e4252'
down_revision = '6d72a0398d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('analyzed_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'analyzed_description')
    # ### end Alembic commands ###
