"""add_structured_resume_info_to_candidates_table

Revision ID: bdedce939ef8
Revises: 770db16e4252
Create Date: 2025-05-17 20:42:52.708680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdedce939ef8'
down_revision = '770db16e4252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('structured_resume_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'structured_resume_info')
    # ### end Alembic commands ###
